### PR TITLE
add more properties to test repository

### PR DESCRIPTION
**Pull request by garemoko**
@jlowe64 please can you check if this does anything to improve the integration tests?

TBH I think I'm going to have to get the integration tests set up myself ~~and completely re-write testRepository.php to be a lot more sophisticated and take the $type parameter into account. But maybe we can avoid that pain for now...~~

### CODE REVIEW

**Comment by ryansmith94** [comment]
Integration tests run on Travis too by the way :smile_cat:

**Comment by ryansmith94** [comment]
Yeah they do, but obviously you'd have to update the dependencies in the main repo.

**Comment by garemoko** [comment]
This is now passing integration tests locally. 

I also had to modify the testCreateEvent method in moodle-logstore_xapi to
```
   public function testCreateEvent() {
        $input = $this->constructInput();

        $moodle_event = $this->moodle_controller->createEvent($input);
        $this->assertTrue($moodle_event != null, 'Check that the event exists in the expander controller.');

        $translator_events = $this->translator_controller->createEvents($moodle_event);

        foreach ($translator_events as $translator_event) {
           $xapi_event = $this->xapi_controller->createEvent($translator_event);
            $this->assertTrue($xapi_event != null, 'Check that the event exists in the emitter controller.');

            $this->assertOutput($input, $xapi_event);
        }
    }
```

I assume @jlowe64 and @micaherne already did this in order for them to get to the errors they were hitting.

**Comment by ryansmith94** [comment]
Awesome, good stuff @garemoko :+1:

**Comment by jlowe64** [comment]
I'll get on this tomorrow and hopefully can push a release out!

**Pull request merged**
