### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by garemoko**
https://github.com/jlowe64/moodle-logstore_xapi/issues/51

### CODE REVIEW

**Comment by garemoko** [comment]
I haven't done tests for this yet.

**Comment by garemoko** [comment]
@ryansmith94 @jlowe64 this is ready for review

**Comment by jlowe64** [comment]
Looks good to me. I'll make a release with my scorm tracking as soon as Moodle finalizes it. 

J

**Comment by ryansmith94** [comment]
Looks good to me too. Nice work @garemoko :+1:

**Comment by ryansmith94** [comment]
Closing because it now includes some commits from #30 that aren't ready to merge.

**Comment by garemoko** [comment]
@ryansmith94 no commits from #30 in here. just some changes to feedbacksubmitted.php to handle the #30 changes when they land.

**Comment by ryansmith94** [comment]
Ah I see, my bad.

**Comment by garemoko** [comment]
@ryansmith94 happy to revert that latest commit and then rebase #30 and include it there if you want to merge this.

**Comment by ryansmith94** [comment]
Yeah that sounds like a better idea @garemoko, then we can get this merged before we forget the dependency between the two.

**Comment by garemoko** [comment]
@ryansmith94 done. And I've committed the changes to the other PR.

**Comment by ryansmith94** [comment]
Awesome thanks Andrew

**Pull request merged**
