### PR TITLE
Add facetoface events

### PR DESCRIPTION
**Pull request by garemoko**
Addresses expander element of https://github.com/xAPI-vle/moodle-logstore_xapi/issues/52

Notes: 
1. Adding/removing of users by admin does not trigger enrol/unenrol event. See https://tracker.moodle.org/browse/CONTRIB-6356 . This must be resolved in the facetoface plugin itself. 
2. I'm ignoring mdl_facetoface_session_data, mdl_facetoface_session_field, mdl_facetoface_session_roles because on my Moodle they have no data and I can't figure out what they are

### CODE REVIEW

**Comment by garemoko** [comment]
@ryansmith94 @jlowe64 ready for review!

**Comment by garemoko** [comment]
Hold off reviewing this; now that I;m doing the translator I realize I don't have the data I need for the attended event

**Comment by garemoko** [comment]
Docs and probably tests are currently out of sync

**Comment by garemoko** [comment]
I've had a shift of priorities and am unlikely to get to this PR for a while (or the translator). I think the two of them are close and if anybody wants to take this across the finish line, I'm very happy to answer any questions.

**Comment by jlowe64** [comment]
I could probably take it on, but I need to push out my scorm tracking first, after all these PRs/releases needing to be updated. So might be in a few weeks?

**Comment by garemoko** [comment]
@jlowe64 @ryansmith94 assuming this passes, it's ready for review. 

I couldn't say for certain that I won't need to add to what's captured again later, but I'd like to get this PR merged and in as a complete thing that we can build on as required.

**Comment by ryansmith94** [comment]
Looks good to me @jlowe64

**Comment by garemoko** [comment]
@jlowe64 I'd love to get this merged sooner rather than later since #36 will build on this fork. (otherwise I'd have a horrific conflict in #36)

**Comment by jlowe64** [comment]
@garemoko I can merge it but I won't be able to make an official release just yet. I am swamped.

**Pull request merged**
