### PR TITLE
Better test repo

### PR DESCRIPTION
**Pull request by garemoko**
Replaces the test repo with a more realistic representation of the Moodle database. 

This doesn't include every possible field, but should be a good foundation for us to add to.

### CODE REVIEW

**Comment by ryansmith94** [comment]
I think we can probably do something slightly better than a huge switch statement.

**Comment by ryansmith94** [comment]
I'd probably just store an associative array on the class like:
```
[
  'users' => [
    'id' => 1
  ]
]
```
Then fetch things like:
```
$assocArray['users'];
```

**Comment by garemoko** [comment]
@ryansmith94 is a huge array of arrays any better than a huge switch?

I mean, really the right technical solution here is to use a database, which is why Moodle has a database,  but I don't think we can do that in travis.

**Comment by garemoko** [comment]
Huh...actually... https://docs.travis-ci.com/user/database-setup/

**Comment by garemoko** [comment]
That's probably overkill though.

**Comment by garemoko** [comment]
@ryansmith94 @jlowe64 this is now ready for review. Once this is merged, I'll work on tests for the new quiz questions.

**Comment by ryansmith94** [comment]
Yeah an array is definitely best, I'd probably stick the array in a JSON file and load it into the test repo @garemoko.

**Comment by garemoko** [comment]
@ryansmith94 this now uses a JSON file. Good to merge?

**Comment by garemoko** [comment]
I'm not sure why the diff includes all the face to face stuff because that has now merged. I'll remake the PR.

**Pull request closed without merging**
