### PR TITLE
Quiz more types

### PR DESCRIPTION
**Pull request by garemoko**
Adds some extra data relating to numeric and match question types in Moodle quizzes. 

Docs and test changes still to do; this probably means having a range of question types in both.

### CODE REVIEW

**Comment by garemoko** [comment]
I'm tempted to not do the docs and tests here until we update the test repository to use more realistic data and get automatic docs working. @ryansmith94 @jlowe64 any thoughts on that?

**Comment by garemoko** [comment]
@ryansmith94 makes sense. 

I guess the order will be
1. Make test repo changes not including support for these new question types.
2. Merge that PR into master and into this PR. I don't envisage any conflict as it will be totally different files. 
3. Add these new question types to the new test repo.

**Comment by ryansmith94** [comment]
Yeah that sounds right to me @garemoko 👍

**Comment by garemoko** [comment]
Obseleted by #38

**Pull request closed without merging**
