### PR TITLE
Adds course completion event and user identification by email

### PR DESCRIPTION
**Pull request by CinecaElearning**
The changes implemented here are about the following issues:
https://github.com/LearningLocker/Moodle-Log-Expander/issues/27
https://github.com/LearningLocker/Moodle-Log-Expander/issues/28

### CODE REVIEW

**Comment by ryansmith94** [comment]
Seems fine.

**Comment by jlowe64** [comment]
As much as we can test, the better, in my opinion.

**Comment by ryansmith94** [comment]
Waiting on that assertion then @CinecaElearning

**Comment by ryansmith94** [comment]
Conflicts likely to be caused by merging #26. Should be easy enough to resolve @jlowe64 once the tests have been added by @CinecaElearning.

**Comment by jlowe64** [comment]
Can do @ryansmith94

**Comment by jlowe64** [comment]
Has been done by: https://github.com/LearningLocker/Moodle-Log-Expander/pull/33

**Pull request closed without merging**
