### PR TITLE
Quiz more types with new test repo

### PR DESCRIPTION
**Pull request by garemoko**
Will superceed #35 once passing.

### CODE REVIEW

**Comment by garemoko** [comment]
@ryansmith94 @jlowe64 This is now ready for review and merge. It doesn't include changes to docs because we should now be able to auto-generate the docs whenever we do a release.

**Comment by jlowe64** [comment]
@garemoko Is the mixture of single and double quotes on purpose, like for PHP reasons or some other reason?

Other than that, I'll merge this ASAP, because I'm running into major issues trying to test my scorm reporting. I didn't realize this not only held tests but also parts of the test repo or else I would have merged this before I started the scorm stuff! My mistake.

**Comment by garemoko** [comment]
The ones in the JSON file are there because JSON. The others are just me being bad. I'll fix.

**Comment by garemoko** [comment]
@jlowe64 This now uses single quotes consistently.

Sorry for the changes to test repo in this PR. I had meant to have that done in the previous PR but once I started using it in practice with the questions I realized that it needed more work.

**Comment by garemoko** [comment]
The fail here isn't a new issue created by this PR, it exists because additional automatic tests have been added. I suggest that refactoring the repository be handled as a separate PR.

**Comment by ryansmith94** [comment]
Yeah I need to add some config to code climate to ignore that issue.

**Comment by garemoko** [comment]
Honestly, i think it's worth addressing - the repo has a bunch of stuff in it that's specific to certain events or groups of events and it can be quite hard to find specific functions. 

Just not in this PR.

**Comment by ryansmith94** [comment]
I don't really have an issue with classes that have really small methods. The repository is essentially a facade for the mongo database in our case and you can't really restrict a facade to 10 methods.

**Comment by jlowe64** [comment]
@ryansmith94 should I just ignore this one codeclimate issue or are you going to configure it to be a little more in line with what we're doing?

**Comment by jlowe64** [comment]
@garemoko thanks for making those changes. The ones in the php methods were what I was talking about.

**Comment by ryansmith94** [comment]
Hey @jlowe64, just configured CodeClimate to remove the error about too many public methods (I've set it up to ignore methods starting with "read").

**Comment by ryansmith94** [comment]
@garemoko if you make a dummy commit, that CodeClimate issue should disappear 👍

**Comment by garemoko** [comment]
Done

**Comment by ryansmith94** [comment]
Hahaha what? It says that you fixed that issue and created it... 😕 ❓

**Comment by ryansmith94** [comment]
Let me try something else

**Comment by ryansmith94** [comment]
Ok should be fixed now.

**Comment by jlowe64** [comment]
@garemoko try again if you can? :)

**Comment by ryansmith94** [comment]
I can't refresh builds on CodeClimate unfortunately.

**Comment by garemoko** [comment]
sorry @ryansmith94

**Comment by ryansmith94** [comment]
Meh ignore code climate for this PR then @jlowe64, we'll have to make a PR to fix all of the issues and see if that helps in future.

**Comment by jlowe64** [comment]
I really doesn't like our 17 methods...

**Comment by jlowe64** [comment]
Alrighty @ryansmith94 it's cool. It's a minor issue anyway!

**Pull request merged**
